### ISSUE TITLE
Not sure why spacy breaks, maybe Cython?

### ISSUE THREAD

**Issue by kootenpv** [laike9m/pdir2#16]
```python
>>> import spacy
>>> nlp=spacy.load("en")
>>> pdir(nlp("I had eaten")[1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pdir/api.py", line 24, in __init__
    source = {name: self.__getattr_wrapper(name) for name in dir(obj)}
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pdir/api.py", line 24, in <dictcomp>
    source = {name: self.__getattr_wrapper(name) for name in dir(obj)}
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pdir/api.py", line 77, in __getattr_wrapper
    return getattr(self.obj, name)
  File "spacy/tokens/token.pyx", line 250, in spacy.tokens.token.Token.has_repvec.__get__ (spacy/tokens/token.cpp:7348)
AttributeError: has_repvec was renamed to has_vector in v0.100
```

I can normally "dir".

**Comment by laike9m** [comment]
This is weird, it's probably related to Cython but I'm not 100% sure. Thanks for reporting it.
